export const SITE = {
  name: "SeoFX",
  tagline: "Sri Lanka's #1 SEO Company",
  url: "https://seofx.lk",
  phone: "+94 777 797 035",
  phoneRaw: "+94777797035",
  phone2: "+94 117 662 526",
  phone2Raw: "+94117662526",
  whatsapp: "+94777797035",
  email: "info@seofx.lk",
  address: "Rajagiriya, Sri Lanka",
};

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "About", href: "/seo-specialist-sri-lanka" },
  { label: "Services", href: "/services" },
  { label: "Industries", href: "/industries" },
  { label: "SEO Consultation", href: "/seo-consultant-sri-lanka" },
  { label: "Pricing", href: "/seo-packages-sri-lanka" },
];

export const FOOTER_LINKS = [
  { label: "Case Studies", href: "/case-studies" },
  { label: "Blog", href: "/blog" },
  { label: "FAQ", href: "/faq" },
];

export const BLOG_POSTS = [
  {
    slug: "best-seo-company-sri-lanka-guide",
    title: "What Makes the Best SEO Company in Sri Lanka? A Complete Guide",
    excerpt: "What truly makes the best SEO company in Sri Lanka? We break down the criteria, red flags, and why SeoFX is trusted by businesses across the island.",
    category: "SEO",
    date: "2025-01-10",
    readTime: "8 min read",
  },
  {
    slug: "seo-sri-lanka-complete-guide-2025",
    title: "SEO in Sri Lanka: The Complete 2025 Guide for Business Owners",
    excerpt: "The complete guide to SEO in Sri Lanka for 2025. Learn how SEO works, why your business needs it, and how to get started with Sri Lanka's expert SEO team.",
    category: "SEO Guide",
    date: "2025-01-12",
    readTime: "9 min read",
  },
  {
    slug: "how-to-choose-seo-company-sri-lanka",
    title: "How to Choose the Right SEO Company in Sri Lanka for Your Business",
    excerpt: "Looking for a reliable SEO company in Sri Lanka? Discover what to look for, what to avoid, and why SeoFX is the #1 choice for Sri Lankan businesses.",
    category: "SEO",
    date: "2025-01-08",
    readTime: "8 min read",
  },
  {
    slug: "top-seo-companies-in-sri-lanka-2025",
    title: "Top SEO Companies in Sri Lanka — What Makes Them Stand Apart in 2025",
    excerpt: "Comparing SEO companies in Sri Lanka? Learn what separates the best from the rest — and why SeoFX consistently leads the pack.",
    category: "SEO",
    date: "2025-01-09",
    readTime: "7 min read",
  },
  {
    slug: "seo-companies-sri-lanka-comparison-guide",
    title: "SEO Companies in Sri Lanka — A Business Owner's Honest Comparison Guide",
    excerpt: "Comparing SEO companies in Sri Lanka for your business? This honest guide covers what to ask, what to pay, and what results to expect.",
    category: "SEO",
    date: "2025-01-11",
    readTime: "8 min read",
  },
  {
    slug: "seo-service-sri-lanka-what-is-included",
    title: "What Does an SEO Service in Sri Lanka Actually Include? A Plain-English Breakdown",
    excerpt: "What does an SEO service in Sri Lanka actually include? We break down every component — keyword research, on-page, link building & more.",
    category: "SEO Services",
    date: "2025-01-13",
    readTime: "8 min read",
  },
  {
    slug: "why-seofx-best-seo-company-in-sri-lanka",
    title: "7 Reasons SeoFX is the Best SEO Company in Sri Lanka for Growing Businesses",
    excerpt: "Why is SeoFX the best SEO company in Sri Lanka? 7 clear reasons — proven results, white-hat methods, custom strategies & more.",
    category: "SEO",
    date: "2025-01-14",
    readTime: "7 min read",
  },
  {
    slug: "seo-packages-sri-lanka-guide",
    title: "SEO Packages in Sri Lanka — What's Available and What's Right for Your Business",
    excerpt: "Explore SEO packages in Sri Lanka — what each includes, what to pay, and how to choose the right plan for your business.",
    category: "SEO Packages",
    date: "2025-01-15",
    readTime: "7 min read",
  },
  {
    slug: "seo-price-sri-lanka-how-much-should-you-pay",
    title: "SEO Price in Sri Lanka — How Much Should You Pay and What Do You Get?",
    excerpt: "How much does SEO cost in Sri Lanka? We break down SEO pricing honestly — from cheap options to premium services — so you can invest wisely.",
    category: "SEO Pricing",
    date: "2025-01-16",
    readTime: "8 min read",
  },
  {
    slug: "what-does-seo-specialist-sri-lanka-do",
    title: "What Does an SEO Specialist in Sri Lanka Actually Do? — Roles, Skills, and What to Expect",
    excerpt: "Wondering what an SEO specialist in Sri Lanka actually does day to day? SeoFX explains the real roles, skills, and results you should expect.",
    category: "SEO Specialist",
    date: "2025-02-01",
    readTime: "9 min read",
  },
  {
    slug: "seo-specialist-vs-seo-agency-sri-lanka",
    title: "SEO Specialist vs SEO Agency in Sri Lanka — Which One Does Your Business Actually Need?",
    excerpt: "Should you hire an SEO specialist or an SEO agency in Sri Lanka? SeoFX breaks down the real differences and which option fits your business goals.",
    category: "SEO Specialist",
    date: "2025-02-05",
    readTime: "9 min read",
  },
  {
    slug: "how-to-find-best-seo-specialist-sri-lanka",
    title: "How to Find the Best SEO Specialist in Sri Lanka — 7 Things to Check Before You Hire",
    excerpt: "Before hiring an SEO specialist in Sri Lanka, check these 7 things. SeoFX reveals what separates real experts from those who waste your time and budget.",
    category: "SEO Specialist",
    date: "2025-02-10",
    readTime: "10 min read",
  },
  {
    slug: "stop-paying-for-leads-seo-lead-generation-sri-lanka",
    title: "Stop Paying for Leads — How SEO Turns Your Website Into a Lead Generation Machine in Sri Lanka",
    excerpt: "Tired of paying for Google Ads & Facebook Ads? Discover how SEO can turn your Sri Lankan business website into a 24/7 lead generation machine.",
    category: "SEO Strategy",
    date: "2024-10-15",
    readTime: "6 min read",
  },
  {
    slug: "seo-before-making-website-sri-lanka",
    title: "Why You Should Plan SEO Before Building Your Business Website in Sri Lanka",
    excerpt: "Building a new website? Discover why you must plan SEO first — and save time, money & effort. Expert advice from SeoFX Sri Lanka.",
    category: "SEO for Beginners",
    date: "2024-09-13",
    readTime: "5 min read",
  },
  {
    slug: "why-online-presence-important-sri-lanka",
    title: "Why a Strong Online Presence Has Never Been More Important for Sri Lankan Businesses",
    excerpt: "Discover why having a strong online presence in Sri Lanka is no longer optional. Learn how SEO helps Sri Lankan businesses grow.",
    category: "Digital Marketing",
    date: "2024-09-12",
    readTime: "5 min read",
  },
  {
    slug: "organic-traffic-importance-sri-lanka",
    title: "Why Organic Search Traffic is the Most Valuable Asset for Your Sri Lankan Business",
    excerpt: "Learn why organic search traffic is more valuable than paid traffic for Sri Lankan businesses. Expert insight from SeoFX.",
    category: "SEO Education",
    date: "2024-09-12",
    readTime: "7 min read",
  },
  {
    slug: "website-lead-generation-sri-lanka",
    title: "6 Ways to Turn Your Website Into a Lead Generation Machine for Your Sri Lankan Business",
    excerpt: "Is your website generating leads? Learn the 6 key steps to turn your Sri Lankan business website into a powerful lead generation machine.",
    category: "Website Optimisation",
    date: "2024-09-12",
    readTime: "6 min read",
  },
  {
    slug: "results-to-expect-from-seo-specialist-sri-lanka",
    title: "What Results Should You Expect From an SEO Specialist in Sri Lanka? — Realistic Timelines and KPIs",
    excerpt: "What should an SEO specialist in Sri Lanka actually deliver — and when? SeoFX sets honest, specific expectations for timelines, KPIs, and what real progress looks like.",
    category: "SEO Specialist",
    date: "2026-04-26",
    readTime: "11 min read",
  },
  {
    slug: "in-house-seo-specialist-vs-outsourcing-sri-lanka",
    title: "In-House SEO Specialist vs Outsourcing to an SEO Agency in Sri Lanka — Pros, Cons, and How to Decide",
    excerpt: "Should you hire an in-house SEO specialist or outsource to an agency in Sri Lanka? SeoFX breaks down the real pros, cons, and how to make the right decision.",
    category: "SEO Specialist",
    date: "2026-04-26",
    readTime: "10 min read",
  },
  {
    slug: "signs-of-good-seo-specialist-sri-lanka",
    title: "8 Signs You Have Found a Genuinely Good SEO Specialist in Sri Lanka",
    excerpt: "How do you know when you've found a genuinely skilled SEO specialist in Sri Lanka? SeoFX identifies 8 clear signs that separate real expertise from convincing presentation.",
    category: "SEO Specialist",
    date: "2026-04-26",
    readTime: "9 min read",
  },
  {
    slug: "what-to-look-for-hiring-seo-company-sri-lanka",
    title: "What to Look for When Hiring an SEO Company in Sri Lanka — A Business Owner's Guide",
    excerpt: "Hiring an SEO company in Sri Lanka? Know exactly what to look for before you commit. SeoFX gives Sri Lankan business owners a clear, honest hiring guide.",
    category: "SEO Company",
    date: "2026-04-26",
    readTime: "10 min read",
  },
  {
    slug: "why-sri-lankan-businesses-get-seo-wrong",
    title: "Why Most Sri Lankan Businesses Get SEO Wrong — and What the Right Approach Actually Looks Like",
    excerpt: "Most Sri Lankan businesses approach SEO incorrectly. SeoFX explains the most common mistakes, why they happen, and what a genuinely effective approach looks like.",
    category: "SEO Company",
    date: "2026-04-26",
    readTime: "9 min read",
  },
  {
    slug: "how-seo-company-sri-lanka-builds-google-presence",
    title: "How an SEO Company in Sri Lanka Should Build Your Long-Term Google Presence — Step by Step",
    excerpt: "How does a professional SEO company in Sri Lanka actually build lasting Google rankings? SeoFX explains the complete process — step by step.",
    category: "SEO Company",
    date: "2026-04-26",
    readTime: "13 min read",
  },
  {
    slug: "seo-sri-lanka-complete-guide-2026",
    title: "SEO Sri Lanka — The Complete Guide to Search Engine Optimisation for Sri Lankan Businesses (2026)",
    excerpt: "The definitive guide to SEO in Sri Lanka. Learn how search engine optimisation works, why Sri Lankan businesses need it, and how to build a strategy that delivers real results.",
    category: "SEO Guide",
    date: "2026-04-26",
    readTime: "14 min read",
  },
  {
    slug: "is-seo-worth-it-sri-lanka",
    title: "Is SEO Worth It for Sri Lankan Businesses? — An Honest Answer With Real Reasoning",
    excerpt: "Is SEO actually worth the investment for your Sri Lankan business? SeoFX gives an honest, no-nonsense answer — including when SEO works, when it doesn't, and what to expect.",
    category: "SEO Guide",
    date: "2026-04-26",
    readTime: "11 min read",
  },
  {
    slug: "seo-sri-lanka-2026-how-google-has-changed",
    title: "How Google Search Has Changed in Sri Lanka — and What Your Business Must Do Differently in 2026",
    excerpt: "Google search in Sri Lanka has changed significantly. SeoFX explains the biggest shifts in 2026 SEO and what Sri Lankan businesses must do to stay visible and competitive.",
    category: "SEO Guide",
    date: "2026-04-26",
    readTime: "11 min read",
  },
  {
    slug: "how-to-choose-seo-company-sri-lanka-questions",
    title: "How to Choose the Right SEO Company in Sri Lanka — 10 Questions to Ask Before You Sign",
    excerpt: "Choosing the right SEO company in Sri Lanka is critical. SeoFX reveals the 10 questions every Sri Lankan business owner must ask before signing with any SEO provider.",
    category: "SEO Company",
    date: "2026-04-26",
    readTime: "12 min read",
  },
  {
    slug: "what-seo-company-sri-lanka-should-deliver",
    title: "What an SEO Company in Sri Lanka Should Deliver in Month 1, Month 3, and Month 6 — Realistic Expectations",
    excerpt: "What should your SEO company actually be delivering each month? SeoFX sets honest, realistic expectations for what good SEO looks like at month 1, 3, and 6 in Sri Lanka.",
    category: "SEO Company",
    date: "2026-04-26",
    readTime: "10 min read",
  },
  {
    slug: "seo-company-sri-lanka-red-flags-green-flags",
    title: "Red Flags and Green Flags: How to Tell a Good SEO Company in Sri Lanka From a Bad One",
    excerpt: "Not all SEO companies in Sri Lanka deliver what they promise. SeoFX reveals the red flags that expose bad providers and the green flags that identify the real ones.",
    category: "SEO Company",
    date: "2026-04-26",
    readTime: "11 min read",
  },
  {
    slug: "seo-services-sri-lanka-what-is-included",
    title: "SEO Services in Sri Lanka — What Is Included, What Is Not, and What You Should Demand From Your Provider",
    excerpt: "What do professional SEO services in Sri Lanka actually include? SeoFX gives a complete, honest breakdown of every component — and what separates real SEO from superficial activity.",
    category: "SEO Services",
    date: "2026-04-26",
    readTime: "13 min read",
  },
  {
    slug: "on-page-vs-off-page-seo-services-sri-lanka",
    title: "On-Page vs Off-Page SEO Services in Sri Lanka — What Each Does and Why Your Business Needs Both",
    excerpt: "What is the difference between on-page and off-page SEO services in Sri Lanka? SeoFX explains what each discipline covers, how they work together, and why both matter.",
    category: "SEO Services",
    date: "2026-04-26",
    readTime: "11 min read",
  },
  {
    slug: "monthly-seo-services-vs-one-time-audit-sri-lanka",
    title: "Monthly SEO Services vs a One-Time SEO Audit in Sri Lanka — Which Is Right for Your Business?",
    excerpt: "Should you invest in monthly SEO services or a one-time audit in Sri Lanka? SeoFX explains the real difference, what each delivers, and how to decide what your business actually needs.",
    category: "SEO Services",
    date: "2026-04-26",
    readTime: "11 min read",
  },
  {
    slug: "why-sri-lankan-business-needs-google-ads-2025",
    title: "Why Every Sri Lankan Business Needs Google Ads in 2025",
    excerpt: "Discover why Google Ads is the fastest growth lever for Sri Lankan businesses in 2025 — instant visibility, intent-based targeting and measurable ROI.",
    category: "Google Ads",
    date: "2026-04-28",
    readTime: "6 min read",
  },
  {
    slug: "how-much-does-google-ads-cost-sri-lanka",
    title: "How Much Does Google Ads Cost in Sri Lanka? A Complete Budget Guide",
    excerpt: "A complete guide to Google Ads cost in Sri Lanka — average CPC by industry, recommended monthly budgets and how to make every rupee count.",
    category: "Google Ads",
    date: "2026-04-28",
    readTime: "6 min read",
  },
  {
    slug: "google-ads-vs-facebook-ads-sri-lanka",
    title: "Google Ads vs. Facebook Ads in Sri Lanka: Which Delivers Better ROI?",
    excerpt: "Should Sri Lankan businesses choose Google Ads or Facebook Ads? A clear comparison of cost, intent, targeting and ROI to help you decide.",
    category: "Google Ads",
    date: "2026-04-28",
    readTime: "6 min read",
  },
  {
    slug: "google-ads-mistakes-sri-lankan-businesses-make",
    title: "5 Common Google Ads Mistakes Sri Lankan Businesses Make (And How to Fix Them)",
    excerpt: "The 5 most common Google Ads mistakes Sri Lankan businesses make — from broad match keywords to no conversion tracking — and how to fix each one.",
    category: "Google Ads",
    date: "2026-04-28",
    readTime: "6 min read",
  },
  {
    slug: "how-to-choose-google-ads-agency-sri-lanka",
    title: "How to Choose the Right Google Ads Agency in Sri Lanka",
    excerpt: "A practical 6-step framework to evaluate any Google Ads agency in Sri Lanka — from credentials and reporting to landing pages and fee structures.",
    category: "Google Ads",
    date: "2026-04-28",
    readTime: "7 min read",
  },
];
