export const SITE = {
  name: "SeoFX",
  tagline: "Sri Lanka's #1 SEO Company",
  url: "https://seofx.lk",
  phone: "+94 777 797 035",
  phoneRaw: "+94777797035",
  phone2: "+94 117 662 526",
  phone2Raw: "+94117662526",
  whatsapp: "+94777797035",
  email: "info@seofx.lk",
  address: "Rajagiriya, Sri Lanka",
};

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "About", href: "/seo-specialist-sri-lanka" },
  { label: "Services", href: "/services" },
  { label: "Pricing", href: "/seo-packages-sri-lanka" },
  { label: "Case Studies", href: "/case-studies" },
  { label: "Blog", href: "/blog" },
  { label: "FAQ", href: "/faq" },
];

export const BLOG_POSTS = [
  {
    slug: "best-seo-company-sri-lanka-guide",
    title: "What Makes the Best SEO Company in Sri Lanka? A Complete Guide",
    excerpt: "What truly makes the best SEO company in Sri Lanka? We break down the criteria, red flags, and why SeoFX is trusted by businesses across the island.",
    category: "SEO",
    date: "2025-01-10",
    readTime: "8 min read",
  },
  {
    slug: "seo-sri-lanka-complete-guide-2025",
    title: "SEO in Sri Lanka: The Complete 2025 Guide for Business Owners",
    excerpt: "The complete guide to SEO in Sri Lanka for 2025. Learn how SEO works, why your business needs it, and how to get started with Sri Lanka's expert SEO team.",
    category: "SEO Guide",
    date: "2025-01-12",
    readTime: "9 min read",
  },
  {
    slug: "how-to-choose-seo-company-sri-lanka",
    title: "How to Choose the Right SEO Company in Sri Lanka for Your Business",
    excerpt: "Looking for a reliable SEO company in Sri Lanka? Discover what to look for, what to avoid, and why SeoFX is the #1 choice for Sri Lankan businesses.",
    category: "SEO",
    date: "2025-01-08",
    readTime: "8 min read",
  },
  {
    slug: "top-seo-companies-in-sri-lanka-2025",
    title: "Top SEO Companies in Sri Lanka — What Makes Them Stand Apart in 2025",
    excerpt: "Comparing SEO companies in Sri Lanka? Learn what separates the best from the rest — and why SeoFX consistently leads the pack.",
    category: "SEO",
    date: "2025-01-09",
    readTime: "7 min read",
  },
  {
    slug: "seo-companies-sri-lanka-comparison-guide",
    title: "SEO Companies in Sri Lanka — A Business Owner's Honest Comparison Guide",
    excerpt: "Comparing SEO companies in Sri Lanka for your business? This honest guide covers what to ask, what to pay, and what results to expect.",
    category: "SEO",
    date: "2025-01-11",
    readTime: "8 min read",
  },
  {
    slug: "seo-service-sri-lanka-what-is-included",
    title: "What Does an SEO Service in Sri Lanka Actually Include? A Plain-English Breakdown",
    excerpt: "What does an SEO service in Sri Lanka actually include? We break down every component — keyword research, on-page, link building & more.",
    category: "SEO Services",
    date: "2025-01-13",
    readTime: "8 min read",
  },
  {
    slug: "why-seofx-best-seo-company-in-sri-lanka",
    title: "7 Reasons SeoFX is the Best SEO Company in Sri Lanka for Growing Businesses",
    excerpt: "Why is SeoFX the best SEO company in Sri Lanka? 7 clear reasons — proven results, white-hat methods, custom strategies & more.",
    category: "SEO",
    date: "2025-01-14",
    readTime: "7 min read",
  },
  {
    slug: "seo-packages-sri-lanka-guide",
    title: "SEO Packages in Sri Lanka — What's Available and What's Right for Your Business",
    excerpt: "Explore SEO packages in Sri Lanka — what each includes, what to pay, and how to choose the right plan for your business.",
    category: "SEO Packages",
    date: "2025-01-15",
    readTime: "7 min read",
  },
  {
    slug: "seo-price-sri-lanka-how-much-should-you-pay",
    title: "SEO Price in Sri Lanka — How Much Should You Pay and What Do You Get?",
    excerpt: "How much does SEO cost in Sri Lanka? We break down SEO pricing honestly — from cheap options to premium services — so you can invest wisely.",
    category: "SEO Pricing",
    date: "2025-01-16",
    readTime: "8 min read",
  },
  {
    slug: "what-does-seo-specialist-sri-lanka-do",
    title: "What Does an SEO Specialist in Sri Lanka Actually Do? — Roles, Skills, and What to Expect",
    excerpt: "Wondering what an SEO specialist in Sri Lanka actually does day to day? SeoFX explains the real roles, skills, and results you should expect.",
    category: "SEO Specialist",
    date: "2025-02-01",
    readTime: "9 min read",
  },
  {
    slug: "seo-specialist-vs-seo-agency-sri-lanka",
    title: "SEO Specialist vs SEO Agency in Sri Lanka — Which One Does Your Business Actually Need?",
    excerpt: "Should you hire an SEO specialist or an SEO agency in Sri Lanka? SeoFX breaks down the real differences and which option fits your business goals.",
    category: "SEO Specialist",
    date: "2025-02-05",
    readTime: "9 min read",
  },
  {
    slug: "how-to-find-best-seo-specialist-sri-lanka",
    title: "How to Find the Best SEO Specialist in Sri Lanka — 7 Things to Check Before You Hire",
    excerpt: "Before hiring an SEO specialist in Sri Lanka, check these 7 things. SeoFX reveals what separates real experts from those who waste your time and budget.",
    category: "SEO Specialist",
    date: "2025-02-10",
    readTime: "10 min read",
  },
  {
    slug: "stop-paying-for-leads-seo-lead-generation-sri-lanka",
    title: "Stop Paying for Leads — How SEO Turns Your Website Into a Lead Generation Machine in Sri Lanka",
    excerpt: "Tired of paying for Google Ads & Facebook Ads? Discover how SEO can turn your Sri Lankan business website into a 24/7 lead generation machine.",
    category: "SEO Strategy",
    date: "2024-10-15",
    readTime: "6 min read",
  },
  {
    slug: "seo-before-making-website-sri-lanka",
    title: "Why You Should Plan SEO Before Building Your Business Website in Sri Lanka",
    excerpt: "Building a new website? Discover why you must plan SEO first — and save time, money & effort. Expert advice from SeoFX Sri Lanka.",
    category: "SEO for Beginners",
    date: "2024-09-13",
    readTime: "5 min read",
  },
  {
    slug: "why-online-presence-important-sri-lanka",
    title: "Why a Strong Online Presence Has Never Been More Important for Sri Lankan Businesses",
    excerpt: "Discover why having a strong online presence in Sri Lanka is no longer optional. Learn how SEO helps Sri Lankan businesses grow.",
    category: "Digital Marketing",
    date: "2024-09-12",
    readTime: "5 min read",
  },
  {
    slug: "organic-traffic-importance-sri-lanka",
    title: "Why Organic Search Traffic is the Most Valuable Asset for Your Sri Lankan Business",
    excerpt: "Learn why organic search traffic is more valuable than paid traffic for Sri Lankan businesses. Expert insight from SeoFX.",
    category: "SEO Education",
    date: "2024-09-12",
    readTime: "7 min read",
  },
  {
    slug: "website-lead-generation-sri-lanka",
    title: "6 Ways to Turn Your Website Into a Lead Generation Machine for Your Sri Lankan Business",
    excerpt: "Is your website generating leads? Learn the 6 key steps to turn your Sri Lankan business website into a powerful lead generation machine.",
    category: "Website Optimisation",
    date: "2024-09-12",
    readTime: "6 min read",
  },
];
